Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -19,11 +19,10 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Set up JDK 17
-        uses: actions/setup-java@v4
+        uses: actions/setup-java@v5
         with:
           distribution: temurin
           java-version: '17'
-          cache: gradle
 
       - name: Set up Android SDK
         uses: android-actions/setup-android@v3
@@ -36,6 +35,14 @@ jobs:
           sdkmanager "platform-tools"
           sdkmanager "platforms;android-35"
           sdkmanager "build-tools;35.0.0"
+
+      - name: Check Gradle Wrapper
+        run: |
+          if [ ! -f "gradlew" ]; then
+            echo "ERROR: gradlew file not found."
+            echo "The Android Gradle project is incomplete."
+            exit 1
+          fi
 
       - name: Make Gradle executable
         run: chmod +x gradlew
